Repository lucee/lucee-docs, pull requests merged in 2022-02, with the labels that each got.

#1221 LD-143 show required extension for functions and tags
  api/data/FunctionPage.cfc
  api/data/TagPage.cfc
  api/reference/FunctionReferenceReader.cfc
  api/reference/TagReferenceReader.cfc
  builders/html/templates/function.cfm
  builders/html/templates/tag.cfm
Labels: enhancement

#1218 fixes doc's search function gets stuck in a loop
  builders/html/assets/Gruntfile.js
  builders/html/assets/css/base.34.min.css
  builders/html/assets/js/base.js
  builders/html/assets/js/base.js.map
  builders/html/assets/js/dist/base.34.min.js
  builders/html/assets/js/src/uberCoolLuceeDocsSearch.js
  server/Application.cfc
Labels: bug

#1224 LD-143 extract tag extensions
  api/reference/TagReferenceReader.cfc
Labels: docs-builder

#1225 add search link for related test cases
  api/build/BuildProperties.cfc
  builders/html/Builder.cfc
Labels: enhancement
